const searchMap = {
    // county names
    'Cache County': 'dfc-cachec',
    'Juab County': 'dfc-juabc',
    'Utah County': 'dfc-utahc',
    'Davis County': 'dfc-davisc',
    'Salt Lake County': 'dfc-saltlakec',
    'Wasatch County': 'dfc-wasatchc',
    'Washington County': 'dfc-washingtonc',
    'Weber County': 'dfc-weberc',

    // city names
    'Cache Junction': ['dfc-cj', 'dfc-cachec'],
    Clarkson: ['dfc-clarkston', 'dfc-cachec'],
    Cornish: ['dfc-cornish', 'dfc-cachec'],
    'Hyde Park': ['dfc-hp', 'dfc-cachec'],
    Hyrum: ['dfc-hyrum', 'dfc-cachec'],
    Lewiston: ['dfc-lewiston', 'dfc-cachec'],
    Logan: ['dfc-logan', 'dfc-cachec'],
    Mendon: ['dfc-mendon', 'dfc-cachec'],
    Millville: ['dfc-millville', 'dfc-cachec'],
    Newton: ['dfc-newton', 'dfc-cachec'],
    Paradise: ['dfc-paradise', 'dfc-cachec'],
    Providence: ['dfc-providence', 'dfc-cachec'],
    Richmond: ['dfc-Richmond', 'dfc-cachec'],
    Smithfield: ['dfc-smithfield', 'dfc-cachec'],
    Trenton: ['dfc-trenton', 'dfc-cachec'],
    Wellsville: ['dfc-wellsville', 'dfc-cachec'],
    Eureka: ['dfc-eureka', 'dfc-juabc'],
    Levan: ['dfc-levan', 'dfc-juabc'],
    Mona: ['dfc-mona', 'dfc-juabc'],
    Nephi: ['dfc-nephi', 'dfc-juabc'],
    Layton: ['dfc-layton', 'dfc-davisc'],
    Bountiful: ['dfc-bountiful', 'dfc-davisc'],
    Centerville: ['dfc-centerville', 'dfc-davisc'],
    Clearfield: ['dfc-clearfield', 'dfc-davisc'],
    Farmington: ['dfc-farmington', 'dfc-davisc'],
    Kaysville: ['dfc-kaysville', 'dfc-davisc'],
    'North Salt Lake': ['dfc-nsl', 'dfc-davisc'],
    Syracuse: ['dfc-syracuse', 'dfc-davisc'],
    'Woods Cross': ['dfc-wc', 'dfc-davisc'],
    Draper: ['dfc-draper', 'dfc-saltlakec'],
    Riverton: ['dfc-riverton', 'dfc-saltlakec'],
    'West Jordan': ['dfc-wj', 'dfc-saltlakec'],
    Herriman: ['dfc-herriman', 'dfc-saltlakec'],
    'Salt Lake City': ['dfc-slc', 'dfc-saltlakec'],
    'Bingham Canyon': ['dfc-bc', 'dfc-saltlakec'],
    'South Jordan': ['dfc-sj', 'dfc-saltlakec'],
    Magna: ['dfc-magna', 'dfc-saltlakec'],
    Midvale: ['dfc-midvale', 'dfc-saltlakec'],
    Sandy: ['dfc-sandy', 'dfc-saltlakec'],
    'West Valley City': ['dfc-wvc', 'dfc-saltlakec'],
    Alpine: ['dfc-alpine', 'dfc-utahc'],
    'American Fork': ['dfc-af', 'dfc-utahc'],
    'Elk Ridge': ['dfc-er', 'dfc-utahc'],
    'Spanish Fork': ['dfc-sf', 'dfc-utahc'],
    Lehi: ['dfc-lehi', 'dfc-utahc'],
    Springville: ['dfc-springville', 'dfc-utahc'],
    'Saratoga Springs': ['dfc-ss', 'dfc-utahc'],
    'Eagle Mountain': ['dfc-em', 'dfc-utahc'],
    'Pleasant Grove': ['dfc-pg', 'dfc-utahc'],
    'Woodland Hills': ['dfc-wh', 'dfc-utahc'],
    Lindon: ['dfc-lindon', 'dfc-utahc'],
    Vineyard: ['dfc-vineyard', 'dfc-utahc'],
    Highland: ['dfc-highland', 'dfc-utahc'],
    Mapleton: ['dfc-mapleton', 'dfc-utahc'],
    Salem: ['dfc-salem', 'dfc-utahc'],
    Payson: ['dfc-payson', 'dfc-utahc'],
    Provo: ['dfc-provo', 'dfc-utahc'],
    Orem: ['dfc-orem', 'dfc-utahc'],
    Santaquin: ['dfc-santaquin', 'dfc-utahc'],
    Elberta: ['dfc-elberta', 'dfc-utahc'],
    Goshen: ['dfc-goshen', 'dfc-utahc'],
    'Cedar Valley': ['dfc-cv', 'dfc-utahc'],
    'Heber City': ['dfc-hc', 'dfc-wasatchc'],
    Midway: ['dfc-midway', 'dfc-wasatchc'],
    Wallsburg: ['dfc-wallsburg', 'dfc-wasatchc'],
    Eden: ['dfc-eden', 'dfc-weberc'],
    Hooper: ['dfc-hooper', 'dfc-weberc'],
    Huntsville: ['dfc-huntsville', 'dfc-weberc'],
    Ogden: ['dfc-ogden', 'dfc-weberc'],
    Roy: ['dfc-roy', 'dfc-weberc'],
    Central: ['dfc-central', 'dfc-washingtonc'],
    'Dammeron Valley': ['dfc-dv', 'dfc-washingtonc'],
    Enterprise: ['dfc-enterprise', 'dfc-washingtonc'],
    Gunlock: ['dfc-gunlock', 'dfc-washingtonc'],
    Hildale: ['dfc-hildale', 'dfc-washingtonc'],
    Hurricane: ['dfc-hurricane', 'dfc-washingtonc'],
    Ivins: ['dfc-ivins', 'dfc-washingtonc'],
    'La Verkin': ['dfc-laverkin', 'dfc-washingtonc'],
    Leeds: ['dfc-leeds', 'dfc-washingtonc'],
    'New Harmony': ['dfc-nh', 'dfc-washingtonc'],
    'Pine Valley': ['dfc-pv', 'dfc-washingtonc'],
    Rockville: ['dfc-rockville', 'dfc-washingtonc'],
    'Saint George': ['dfc-sg', 'dfc-washingtonc'],
    'Santa Clara': ['dfc-sc', 'dfc-washingtonc'],
    Springdale: ['dfc-springdale', 'dfc-washingtonc'],
    Toquerville: ['dfc-toquerville', 'dfc-washingtonc'],
    Veyo: ['dfc-veyo', 'dfc-washingtonc'],
    Virgin: ['dfc-virgin', 'dfc-washingtonc'],
    Washington: ['dfc-washington', 'dfc-washingtonc'],

    // zipcodes
    84004: ['dfc-alpine', 'dfc-utahc'],
    84003: ['dfc-af', 'dfc-highland', 'dfc-utahc'],
    84006: ['dfc-bc', 'dfc-saltlakec'],
    84010: ['dfc-bountiful', 'dfc-davisc'],
    84011: ['dfc-bountiful', 'dfc-davisc'],
    84304: ['dfc-cj', 'dfc-cachec'],
    84013: ['dfc-cv', 'dfc-utahc'],
    84014: ['dfc-centerville', 'dfc-davisc'],
    84722: ['dfc-central', 'dfc-washingtonc'],
    84305: ['dfc-clarkston', 'dfc-cachec'],
    84015: ['dfc-clearfield', 'dfc-davisc'],
    84016: ['dfc-clearfield', 'dfc-davisc'],
    84089: ['dfc-clearfield', 'dfc-davisc'],
    84308: ['dfc-cornish', 'dfc-cachec'],
    84783: ['dfc-dv', 'dfc-washingtonc'],
    84020: ['dfc-draper', 'dfc-saltlakec'],
    84005: ['dfc-em', 'dfc-utahc'],
    84310: ['dfc-eden', 'dfc-weberc'],
    84626: ['dfc-elberta', 'dfc-utahc'],
    84725: ['dfc-enterprise', 'dfc-washingtonc'],
    84628: ['dfc-eureka', 'dfc-juabc'],
    84025: ['dfc-farmington', 'dfc-davisc'],
    84633: ['dfc-goshen', 'dfc-utahc'],
    84733: ['dfc-gunlock', 'dfc-washingtonc'],
    84032: ['dfc-hc', 'dfc-wasatchc'],
    84096: ['dfc-herriman', 'dfc-saltlakec'],
    84062: ['dfc-highland', 'dfc-pg', 'dfc-utahc'],
    84784: ['dfc-hildale', 'dfc-washingtonc'],
    84315: ['dfc-hooper', 'dfc-weberc'],
    84317: ['dfc-huntsville', 'dfc-weberc'],
    84737: ['dfc-hurricane', 'dfc-washingtonc'],
    84318: ['dfc-hp', 'dfc-cachec'],
    84319: ['dfc-hyrum', 'dfc-cachec'],
    84738: ['dfc-ivins', 'dfc-washingtonc'],
    84037: ['dfc-kaysville', 'dfc-davisc'],
    84745: ['dfc-laverkin', 'dfc-washingtonc'],
    84040: ['dfc-layton', 'dfc-davisc'],
    84041: ['dfc-layton', 'dfc-davisc'],
    84746: ['dfc-leeds', 'dfc-washingtonc'],
    84043: ['dfc-lehi', 'dfc-utahc'],
    84639: ['dfc-levan', 'dfc-juabc'],
    84320: ['dfc-Lewiston', 'dfc-cachec'],
    84042: ['dfc-lindon', 'dfc-utahc'],
    84321: ['dfc-logan', 'dfc-cachec'],
    84322: ['dfc-logan', 'dfc-providence', 'dfc-cachec'],
    84323: ['dfc-logan', 'dfc-cachec'],
    84341: ['dfc-logan', 'dfc-cachec'],
    84044: ['dfc-magna', 'dfc-saltlakec'],
    84644: ['dfc-mapleton', 'dfc-utahc'],
    84325: ['dfc-mendon', 'dfc-cachec'],
    84047: ['dfc-midvale', 'dfc-saltlakec'],
    84049: ['dfc-midway', 'dfc-wasatchc'],
    84326: ['dfc-millville', 'dfc-cachec'],
    84645: ['dfc-mona', 'dfc-juabc'],
    84648: ['dfc-nephi', 'dfc-juabc'],
    84757: ['dfc-nh', 'dfc-washingtonc'],
    84327: ['dfc-newton', 'dfc-cachec'],
    84054: ['dfc-nsl', 'dfc-davisc'],
    84201: ['dfc-ogden', 'dfc-weberc'],
    84244: ['dfc-ogden', 'dfc-weberc'],
    84401: ['dfc-ogden', 'dfc-weberc'],
    84402: ['dfc-ogden', 'dfc-weberc'],
    84403: ['dfc-ogden', 'dfc-weberc'],
    84404: ['dfc-ogden', 'dfc-weberc'],
    84405: ['dfc-ogden', 'dfc-weberc'],
    84407: ['dfc-ogden', 'dfc-weberc'],
    84408: ['dfc-ogden', 'dfc-weberc'],
    84409: ['dfc-ogden', 'dfc-weberc'],
    84412: ['dfc-ogden', 'dfc-weberc'],
    84414: ['dfc-ogden', 'dfc-weberc'],
    84415: ['dfc-ogden', 'dfc-weberc'],
    84057: ['dfc-orem', 'dfc-vineyard', 'dfc-utahc'],
    84058: ['dfc-orem', 'dfc-utahc'],
    84059: ['dfc-orem', 'dfc-utahc'],
    84097: ['dfc-orem', 'dfc-utahc'],
    84328: ['dfc-paradise', 'dfc-cachec'],
    84651: ['dfc-payson', 'dfc-er', 'dfc-utahc'],
    84781: ['dfc-pv', 'dfc-washingtonc'],
    84601: ['dfc-provo', 'dfc-utahc'],
    84602: ['dfc-provo', 'dfc-utahc'],
    84603: ['dfc-provo', 'dfc-utahc'],
    84604: ['dfc-provo', 'dfc-utahc'],
    84605: ['dfc-provo', 'dfc-utahc'],
    84606: ['dfc-provo', 'dfc-utahc'],
    84333: ['dfc-richmond', 'dfc-cachec'],
    84065: ['dfc-riverton', 'dfc-saltlakec'],
    84763: ['dfc-rockville', 'dfc-washingtonc'],
    84067: ['dfc-roy', 'dfc-weberc'],
    84770: ['dfc-sg', 'dfc-washingtonc'],
    84771: ['dfc-sg', 'dfc-washingtonc'],
    84790: ['dfc-sg', 'dfc-washingtonc'],
    84791: ['dfc-sg', 'dfc-washingtonc'],
    84653: ['dfc-salem', 'dfc-wh', 'dfc-utahc'],
    84101: ['dfc-slc', 'dfc-saltlakec'],
    84102: ['dfc-slc', 'dfc-saltlakec'],
    84103: ['dfc-slc', 'dfc-saltlakec'],
    84104: ['dfc-slc', 'dfc-saltlakec'],
    84105: ['dfc-slc', 'dfc-saltlakec'],
    84106: ['dfc-slc', 'dfc-saltlakec'],
    84107: ['dfc-slc', 'dfc-saltlakec'],
    84108: ['dfc-slc', 'dfc-saltlakec'],
    84109: ['dfc-slc', 'dfc-saltlakec'],
    84110: ['dfc-slc', 'dfc-saltlakec'],
    84111: ['dfc-slc', 'dfc-saltlakec'],
    84112: ['dfc-slc', 'dfc-saltlakec'],
    84113: ['dfc-slc', 'dfc-saltlakec'],
    84114: ['dfc-slc', 'dfc-saltlakec'],
    84115: ['dfc-slc', 'dfc-saltlakec'],
    84116: ['dfc-slc', 'dfc-saltlakec'],
    84117: ['dfc-slc', 'dfc-saltlakec'],
    84118: ['dfc-slc', 'dfc-saltlakec'],
    84121: ['dfc-slc', 'dfc-saltlakec'],
    84122: ['dfc-slc', 'dfc-saltlakec'],
    84123: ['dfc-slc', 'dfc-saltlakec'],
    84124: ['dfc-slc', 'dfc-saltlakec'],
    84125: ['dfc-slc', 'dfc-saltlakec'],
    84126: ['dfc-slc', 'dfc-saltlakec'],
    84127: ['dfc-slc', 'dfc-saltlakec'],
    84129: ['dfc-slc', 'dfc-saltlakec'],
    84130: ['dfc-slc', 'dfc-saltlakec'],
    84131: ['dfc-slc', 'dfc-saltlakec'],
    84132: ['dfc-slc', 'dfc-saltlakec'],
    84133: ['dfc-slc', 'dfc-saltlakec'],
    84134: ['dfc-slc', 'dfc-saltlakec'],
    84138: ['dfc-slc', 'dfc-saltlakec'],
    84139: ['dfc-slc', 'dfc-saltlakec'],
    84141: ['dfc-slc', 'dfc-saltlakec'],
    84143: ['dfc-slc', 'dfc-saltlakec'],
    84145: ['dfc-slc', 'dfc-saltlakec'],
    84147: ['dfc-slc', 'dfc-saltlakec'],
    84148: ['dfc-slc', 'dfc-saltlakec'],
    84150: ['dfc-slc', 'dfc-saltlakec'],
    84151: ['dfc-slc', 'dfc-saltlakec'],
    84152: ['dfc-slc', 'dfc-saltlakec'],
    84157: ['dfc-slc', 'dfc-saltlakec'],
    84158: ['dfc-slc', 'dfc-saltlakec'],
    84165: ['dfc-slc', 'dfc-saltlakec'],
    84170: ['dfc-slc', 'dfc-saltlakec'],
    84171: ['dfc-slc', 'dfc-saltlakec'],
    84180: ['dfc-slc', 'dfc-saltlakec'],
    84184: ['dfc-slc', 'dfc-saltlakec'],
    84190: ['dfc-slc', 'dfc-saltlakec'],
    84199: ['dfc-slc', 'dfc-saltlakec'],
    84070: ['dfc-sandy', 'dfc-saltlakec'],
    84090: ['dfc-sandy', 'dfc-saltlakec'],
    84091: ['dfc-sandy', 'dfc-saltlakec'],
    84092: ['dfc-sandy', 'dfc-saltlakec'],
    84093: ['dfc-sandy', 'dfc-saltlakec'],
    84094: ['dfc-sandy', 'dfc-saltlakec'],
    84765: ['dfc-sc', 'dfc-washingtonc'],
    84655: ['dfc-santaquin', 'dfc-utahc'],
    84045: ['dfc-ss', 'dfc-utahc'],
    84335: ['dfc-smithfield', 'dfc-cachec'],
    84009: ['dfc-sj', 'dfc-saltlakec'],
    84095: ['dfc-sj', 'dfc-saltlakec'],
    84660: ['dfc-sf', 'dfc-utahc'],
    84767: ['dfc-springdale', 'dfc-washingtonc'],
    84663: ['dfc-springville', 'dfc-utahc'],
    84075: ['dfc-syracuse', 'dfc-davisc'],
    84774: ['dfc-toquerville', 'dfc-washingtonc'],
    84338: ['dfc-trenton', 'dfc-cachec'],
    84782: ['dfc-veyo', 'dfc-washingtonc'],
    84779: ['dfc-virgin', 'dfc-washingtonc'],
    84082: ['dfc-wallsburg', 'dfc-wasatchc'],
    84780: ['dfc-washington', 'dfc-washingtonc'],
    84339: ['dfc-wellsville', 'dfc-cachec'],
    84081: ['dfc-wj', 'dfc-saltlakec'],
    84084: ['dfc-wj', 'dfc-saltlakec'],
    84088: ['dfc-wj', 'dfc-saltlakec'],
    84119: ['dfc-wvc', 'dfc-saltlakec'],
    84120: ['dfc-wvc', 'dfc-saltlakec'],
    84128: ['dfc-wvc', 'dfc-saltlakec'],
    84087: ['dfc-wc', 'dfc-davisc'],
};

export default searchMap;
